
# compose example: https://github.com/microsoft/sql-server-samples/blob/master/samples/containers/replication/docker-compose.yml
version: '1'
services:
  db:
    image: 'mcr.microsoft.com/mssql/server:2022-latest'
    container_name: 'filebin_mssql_db'
    hostname: 'db'
    ports:
      - '2600:1533'
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    environment:
      SA_PASSWORD: "test123"
      ACCEPT_EULA: "Y"
      MSSQL_AGENT_ENABLED: "true"