--INSERT INTO [Filebin].[dbo].[test] (name, timestamp)
--VALUES ('!!! HELLO WORLD !!!', CURRENT_TIMESTAMP);
--
--INSERT INTO [Filebin].[dbo].[users] (username, password, enabled)
--VALUES ('admin', 'my_super_secret_password_1234_$%@!', 1);
--
--INSERT INTO [Filebin].[dbo].[users] (username, password, enabled)
--VALUES ('user', 'password', 1);
--
--INSERT INTO [Filebin].[dbo].[authorities] (username, authority)
--VALUES ('admin', 'ROLE_ADMIN');
--
--INSERT INTO [Filebin].[dbo].[authorities] (username, authority)
--VALUES ('user', 'ROLE_USER');
--
--
--
--
